baseURL = 'https://teatrantrakt.github.io/'
languageCode = 'pl-pl'
title = 'Teatr Antrakt'
theme = 'hugo-coder'
defaultcontentlanguage = "pl-pl"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Teatr Antrakt"
  info = "Studencki teatr UMK od 2022"
  description = "Strona Teatru Antrakt"
  keywords = "theatre,teatr,student,fanpage"
  avatarurl = "images/logo.png"

  faviconSVG = "/images/favicon.ico"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[params.lightgallery.defaults]
  thumbsize = "200x200"
  thumbtype = "fill"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Facebook"
  icon = "fa-brands fa-square-facebook fa-2x"
  weight = 1
  url = "https://www.facebook.com/profile.php?id=100083047405294"
[[params.social]]
  name = "Instagram"
  icon = "fa-brands fa-square-instagram fa-2x"
  weight = 2
  url = "https://www.instagram.com/teatr_antrakt/"
[[params.social]]
  name = "YouTube"
  icon = "fa-brands fa-square-youtube fa-2x"
  weight = 3
  url = "https://www.youtube.com/@teatrantrakt"
[[params.social]]
  name = "Bandcamp"
  icon = "fa-brands fa-bandcamp fa-2x"
  weight = 4
  url = "https://antraktteatr.bandcamp.com/album/nie-opuszczaj-mnie"

# Menu links
[[menu.main]]
  name = "Spektakle"
  weight = 2
  url  = "performances/"
[[menu.main]]
  name = "O nas"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Cz≈Çonkowie"
  weight = 3
  url = "members/"
# [[menu.main]]
#   name = "Galeria"
#   weight = 4
#   url = "gallerysite/"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
